### ISSUE TITLE
details key feature page

### ISSUE THREAD

**Issue by sunny7899** [PorePranav/CampusUnify#11]
Hi @PorePranav  Can you assign this issue to me with Hactoberfest tag, or you can assign any other relevant issue? on click of this i can opne this page in detail

<img width="302" alt="image" src="https://github.com/user-attachments/assets/d8bc7e8e-ca01-44e0-ad14-64004c3d4d25">

**Comment by PorePranav** [comment]
Hi @sunny7899,
Could you elaborate on what you wish to add? Like it's just a card to show feature of the application, I don't understand why it would be necessary to create an entire page just to explain a feature.
