### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by vverma022** [PorePranav/CampusUnify#14]
Add Docker support to containerize both the frontend and backend services.

### Tasks:
- Create a Dockerfile for the frontend to build and serve the app.
- Create a Dockerfile for the backend to run the server.
- Set up docker-compose.yml for both services and networking.
- Test and ensure both containers work together.

### Acceptance Criteria:
- Dockerfiles and Docker Compose are added.
- Services run and communicate via docker-compose up.
- Documentation is updated.

**Comment by vverma022** [comment]
Can I be assigned this issue under hacktoberfest and GSSoC ' 24

**Comment by PorePranav** [comment]
Hi @vverma022 
Thank you for your inputs, you can go forward with it. Make sure that you handle the environment variables correctly! Assigning to you.
