### ISSUE TITLE
Login component exceeds the page width in mobile view

### ISSUE THREAD

**Issue by shreyansh1410** [PorePranav/CampusUnify#2]
![Screenshot_20241004_085433_Chrome](https://github.com/user-attachments/assets/c84cdd5b-4252-4b48-b839-c4168c1fa382)

**Comment by shreyansh1410** [comment]
It would be great if you assign this issue to me with the hacktoberfest tag

**Comment by PorePranav** [comment]
Hi @shreyansh1410 
Thank you for bringing these issues to my attention! I’m aware that the current layout is not optimized for mobile devices. I’m planning to make the entire CampusUnify website responsive in phases, ensuring proper testing and functionality along the way.

If you're interested, I can create a separate issue specifically for working on the entire website's responsiveness and assign it to you. It would be great to collaborate on improving the mobile experience across the entire platform.

Let me know if that works for you, and I'll set it up. Thanks again for your valuable feedback and patience!
