### ISSUE TITLE
The frontend is not responsive for the hero image and testimonial section

### ISSUE THREAD

**Issue by w0wayush** [PorePranav/CampusUnify#20]
Text overflow in smaller screen sizes

![image](https://github.com/user-attachments/assets/a2f267dc-6ad7-44dc-80cd-97bd886d4b22)

![image](https://github.com/user-attachments/assets/f51364c6-140c-46e7-b154-f55aff0a308b)

Assign this issue to me and add necessary labels of hacktober fest.

**Comment by PorePranav** [comment]
We have people already working on this issue, please check all the open and closed issues before opening one. Thank you!
