### ISSUE TITLE
Implementation Of Dark Mode Feature

### ISSUE THREAD

**Issue by Prachirsh** [PorePranav/CampusUnify#21]
The dark mode feature allows users to toggle between light and dark themes, enhancing user experience and reducing eye strain, especially in low-light conditions. This feature can be integrated into the existing UI, enabling users to choose their preferred viewing option. I also worked on this before. Can you assign it to me?

**Comment by PorePranav** [comment]
Thank you for opening up and issue, but we have already people working on the same issue in #6. Closing this one!
