### ISSUE TITLE
Password Eye Icon  + Style on Logout

### ISSUE THREAD

**Issue by saarakhan** [PorePranav/CampusUnify#23]
- Password Eye Icon to show or hide the password.

- In the Profile card, some  animation line on logout and Delete Account

I would like to work on this issue assign this to me please under hactoberfest

**Comment by PorePranav** [comment]
Hey @saarakhan,

Thank you for opening this issue! It’s a great suggestion. I’ll go ahead and assign it to you. However, please keep in mind that if the animations or changes don't fit well with the design, I may not be able to merge the PR.

I recommend working in phases and sharing updates before committing the entire code. This way, we can ensure everything aligns well with the project.

Feel free to ask if you need any clarification.

Thank you!

**Comment by saarakhan** [comment]
sure , can you please add gssoc-ext label
