### ISSUE TITLE
Implement Password Hashing for Enhanced Security

### ISSUE THREAD

**Issue by Preetibansal08** [PorePranav/CampusUnify#27]
Currently, the CampusUnify platform stores user passwords in plaintext, which poses a serious security risk. Plaintext passwords leave user accounts vulnerable if the database is compromised. To enhance security and protect user data, we should implement password hashing.

# Proposed Solution
1. Use bcrypt for Password Hashing:
   - Install `bcrypt` to hash passwords before storing them in the database.
   - Use salt rounds to add an extra layer of security.

2. Update User Registration:
   - Modify the registration process to hash passwords before saving them.

3. Update User Login:
   - Use bcrypt's `compare` method to validate passwords during login.

4. Migrate Existing User Data**:
   - Implement a process to convert existing plaintext passwords to hashed passwords.
   - Notify users if a password reset is required.

#Benefits
- Enhanced data security by reducing risk in case of a database breach.
- Industry-standard best practice for storing user credentials.
- Improved user confidence in the platform’s security measures.

 Sample Code
##javascript
const bcrypt = require('bcrypt');
const saltRounds = 10;

// Example for hashing a password
app.post('/register', async (req, res) => {
    const { username, password } = req.body;
    const hashedPassword = await bcrypt.hash(password, saltRounds);
    // Save username and hashedPassword to the database
});

// Example for password comparison during login
app.post('/login', async (req, res) => {
    const { username, password } = req.body;
    const user = await User.findOne({ username: username });
    if (user && await bcrypt.compare(password, user.password)) {
        res.send('Login successful!');
    } else {
        res.send('Invalid credentials');
    }
});
#Expected Outcome
  - Improved Security: The risk of exposing user credentials is minimized.
  - Compliance: By following best practices, we align with industry standards for data security.
  - User Confidence: Enhanced security measures provide users with confidence that their data is protected.

**Comment by Preetibansal08** [comment]
Hi, I would like to be assigned to this issue for implementing password hashing for enhanced security. Thank you!

**Comment by PorePranav** [comment]
Hey @Preetibansal08,
The platform already implements password hashing using bcrypt, and plaintext passwords are not stored. Please ensure you've properly verified and tested the existing implementation before opening issues like this. If you encounter any actual problems, provide specific details for review.
