### ISSUE TITLE
Capacity text and the number overlap in mobile view 

### ISSUE THREAD

**Issue by shreyansh1410** [PorePranav/CampusUnify#3]
![Screenshot_20241004_090145_Chrome](https://github.com/user-attachments/assets/5ce0fc7c-24cc-47bd-b429-82d5a395d14c)

**Comment by shreyansh1410** [comment]
I can work on this if you assign this to me with hacktoberfest tag

**Comment by PorePranav** [comment]
Hi @shreyansh1410,
As mentioned in issue #2, the same applies here. If you wish to go forward with making the site responsive, I'll be happy to create a new issue and it to assign you under hacktoberfest tag.

**Comment by shreyansh1410** [comment]
Yeah sure, I'll start working on it by evening

**Comment by PorePranav** [comment]
I have created issue #4, please take a moment to check out the new issue and interact with it so that I can assign the issue to you and mention you in the comments as and when necessary.
