### ISSUE TITLE
addition of real-time password strength analysis feature

### ISSUE THREAD

**Issue by yalsik86** [PorePranav/CampusUnify#30]
Implementation of real-time password strength analysis feature for login page.

@PorePranav please assign me this issue and label as hacktoberfest.

**Comment by PorePranav** [comment]
Hi @yalsik86,

Thank you for your suggestion and interest in improving the platform. While a real-time password strength analysis feature is a great enhancement, it is not a requirement for the login page at this time. Hence, I won't be able to continue with this issue.
