### ISSUE TITLE
Disable Past Dates and Add Date-Time Input in Event Creation Form

### ISSUE THREAD

**Issue by PorePranav** [PorePranav/CampusUnify#38]
### Description:
In the frontend of the project, when a club creates an event, the current implementation allows selecting a past date, which can lead to incorrect event scheduling. Although the backend rejects dates in the past, it would enhance the user experience to disable past date selection in the UI. Additionally, the form currently lacks a proper way to input both date and time together.

### Proposed Solution:
1. **Disable past dates:**
   - Use `react-day-picker` to implement a date picker that disables selection of any past dates.

2. **Date and Time input in a single field:**
   - Combine date and time into a single input field where users can pick a date (with past dates disabled) and input a time. Ensure the format is compatible with the backend API.

### Acceptance Criteria:
- The date picker should prevent selecting any date before the current day.
- The event creation form should include a single field where the user can select both date and time.
- The form should submit the selected date and time together to the backend for event creation.

### Additional Information:
- Use [react-day-picker](https://react-day-picker.js.org/) to handle the date selection and ensure past dates are disabled.
- Implement a time input in the same field for better UX.

**Comment by Adebesin-Cell** [comment]
Hey @PorePranav, 

I’d like to take on this issue! Could you please assign it to me? 

Thanks!

**Comment by PorePranav** [comment]
Assigning to you, good luck! @Adebesin-Cell
