### ISSUE TITLE
Include CODE_OF_CONDUCT file

### ISSUE THREAD

**Issue by Dhruv-Davda** [PorePranav/CampusUnify#41]
I would like to add CODE_OF_CONDUCT file in your repository. 

@PorePranav Could you please assign me this issue ?

**Comment by PorePranav** [comment]
Hi @Dhruv-Davda,
Thank you for your suggestion to add a code of conduct. It's definitely something important for the project. However, it's a good practice for the project maintainer to add it, so I will take care of that shortly. Also, please ensure to check all open and closed issues before opening a new one, to avoid duplicates.

Thank you!
