### ISSUE TITLE
Add Footer to UI and Update Page Design

### ISSUE THREAD

**Issue by Shubham0523** [PorePranav/CampusUnify#44]
I am proposing the addition of a footer to the user interface (UI) along with a new design for the page. The footer will improve navigation and provide a consistent layout across the site.

Changes Proposed:
- Footer Component: Introduce a new footer to enhance usability and provide important links and information.
- Page Design Update: Implement the new design to improve the visual appeal and user experience across all devices.

Benefits:
- Improves overall navigation and access to important links.
- Provides a consistent and professional design across the application.
- Ensures responsive design for optimal viewing on mobile and desktop devices.

![Page Footer Design - v0 by Vercel - Brave 16-10-2024 03_23_47](https://github.com/user-attachments/assets/ac9df86b-5b04-482a-85a5-394a65df6cd3)

**Comment by Shubham0523** [comment]
@PorePranav please assign me this issue

**Comment by PorePranav** [comment]
Hey @Shubham0523,

Thanks for opening up the issue, but I don't think that such a footer is required as of now. Hence, I won't be able to move forward with this issue at the moment. Thank you for understanding!
