### ISSUE TITLE
Header is collides with the content in the mobile design.

### ISSUE THREAD

**Issue by arun0452** [PorePranav/CampusUnify#46]
The header collides with the body content in responsive mode. Is there going to be a change in header format?. Or may I fix this issue?

<img width="940" alt="Screenshot 2024-10-19 at 6 38 27 PM" src="https://github.com/user-attachments/assets/885760c3-f2a2-4099-827e-993566770040">

**Comment by log1-codes** [comment]
@PorePranav  hey kindly assign it to me ... i make sure that i am the best for the responsive designs.here is the proof of work  that i have done  (https://voting-app-65gn.onrender.com/)

**Comment by PorePranav** [comment]
@arun0452 

Thank you for opening up the issue, however, the bug is due to the fact that the website is not currently responsive. I already have other people working on the same issue, hence I won't be able to move forward with this one.
