### ISSUE TITLE
enhancement in app or readme update

### ISSUE THREAD

**Issue by sunny7899** [PorePranav/CampusUnify#7]
Hi @PorePranav Can you assign this issue to me with Hactoberfest tag, or you can assign any other relevant issue?

**Comment by PorePranav** [comment]
Hi @sunny7899.
Could you please elaborate on what changes you wish to propose in the app or README section? It would be helpful for me to understand your ideas better. Also, please take a moment to review [Contributing Guidelines](https://github.com/PorePranav/CampusUnify/blob/main/CONTRIBUTING.md) to get more context.

**Comment by sunny7899** [comment]
I Can do formatting on readme file like this @PorePranav 

![image](https://github.com/user-attachments/assets/23c9aea7-a930-4f83-a476-a6f73e9bac54)

**Comment by PorePranav** [comment]
Thanks for the suggestion, but I don't think I currently need that in README of the repository. If you have any specific issue, feature request or wish to contribute to any specific module, please open a new issue. I will be closing this one.
